//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CD_Tipo_Pregunta
    {
        public TB_CD_Tipo_Pregunta()
        {
            this.TB_CD_Item = new HashSet<TB_CD_Item>();
        }
    
        public int id { get; set; }
        public string tipo_pregunta { get; set; }
    
        public virtual ICollection<TB_CD_Item> TB_CD_Item { get; set; }
    }
}
