//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CD_Item
    {
        public System.Guid id { get; set; }
        public string pregunta { get; set; }
        public int FK_TipoPregunta { get; set; }
    
        public virtual TB_CD_Tipo_Pregunta TB_CD_Tipo_Pregunta { get; set; }
    }
}
